//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Libs.Models.DataStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Insurance
    {
        public long ID { get; set; }
        public long RequestorID { get; set; }
        public int ICID { get; set; }
        public string Folio { get; set; }
        public string InsureKey { get; set; }
        public string InsureNo { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Location { get; set; }
        public string OccupationCode { get; set; }
        public string ActivityCode { get; set; }
        public string PresentCode { get; set; }
        public string TSRCode { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssueMemo { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
