//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Libs.Models.DataStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_External
    {
        public long ID { get; set; }
        public string UserGUID { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Name { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string WeChatID { get; set; }
        public string QQ { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string LicencePlateNumber { get; set; }
        public string PortraitsUrl { get; set; }
        public string PortraitsThumbUrl { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
