//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Libs.Models.DataStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Payment
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<int> PayMethod { get; set; }
        public string PayFolio { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
