//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Libs.Models.DataStores
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Route
    {
        public long ID { get; set; }
        public string RouteGUID { get; set; }
        public Nullable<int> RouteType { get; set; }
        public string From_Province { get; set; }
        public string From_City { get; set; }
        public string From_District { get; set; }
        public string From_Location { get; set; }
        public Nullable<double> From_Longitude { get; set; }
        public Nullable<double> From_Latitude { get; set; }
        public string To_Province { get; set; }
        public string To_City { get; set; }
        public string To_District { get; set; }
        public string To_Location { get; set; }
        public Nullable<double> To_Longitude { get; set; }
        public Nullable<double> To_Latitude { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> RepeatType { get; set; }
        public Nullable<int> RepeatCondition { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<int> SeatCount { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsLongTerm { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
