//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.TaskConsole.MetLisfeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://icare-uat.metlife.com.cn/services/YSW2ICareSave", ConfigurationName="MetLisfeService.YSW2ICareSave")]
    public interface YSW2ICareSave {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://webservices.ec.sinosoft.com) of message doRequestRequest does not match the default value (http://icare-uat.metlife.com.cn/services/YSW2ICareSave)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse doRequest(SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse> doRequestAsync(SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doRequest", WrapperNamespace="http://webservices.ec.sinosoft.com", IsWrapped=true)]
    public partial class doRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlInput;
        
        public doRequestRequest() {
        }
        
        public doRequestRequest(string xmlInput) {
            this.xmlInput = xmlInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doRequestResponse", WrapperNamespace="http://icare-uat.metlife.com.cn/services/YSW2ICareSave", IsWrapped=true)]
    public partial class doRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string doRequestReturn;
        
        public doRequestResponse() {
        }
        
        public doRequestResponse(string doRequestReturn) {
            this.doRequestReturn = doRequestReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YSW2ICareSaveChannel : SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YSW2ICareSaveClient : System.ServiceModel.ClientBase<SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave>, SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave {
        
        public YSW2ICareSaveClient() {
        }
        
        public YSW2ICareSaveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YSW2ICareSaveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YSW2ICareSaveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YSW2ICareSaveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave.doRequest(SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest request) {
            return base.Channel.doRequest(request);
        }
        
        public string doRequest(string xmlInput) {
            SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest inValue = new SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest();
            inValue.xmlInput = xmlInput;
            SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse retVal = ((SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave)(this)).doRequest(inValue);
            return retVal.doRequestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse> SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave.doRequestAsync(SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest request) {
            return base.Channel.doRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SNS.Apps.TaskConsole.MetLisfeService.doRequestResponse> doRequestAsync(string xmlInput) {
            SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest inValue = new SNS.Apps.TaskConsole.MetLisfeService.doRequestRequest();
            inValue.xmlInput = xmlInput;
            return ((SNS.Apps.TaskConsole.MetLisfeService.YSW2ICareSave)(this)).doRequestAsync(inValue);
        }
    }
}
