//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Libs.Models.DataStores_Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WXMessage
    {
        public long ID { get; set; }
        public string From_OpenID { get; set; }
        public Nullable<long> From_UserID { get; set; }
        public string To_OpenID { get; set; }
        public Nullable<long> To_UserID { get; set; }
        public Nullable<long> MsgID { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
