//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route_Matrix
    {
        public long ID { get; set; }
        public long RouteID { get; set; }
        public long MatrixID { get; set; }
        public Nullable<double> Rate_DateTime { get; set; }
        public Nullable<double> Rate_Distance { get; set; }
        public Nullable<bool> IsInformed { get; set; }
        public Nullable<int> InformCount { get; set; }
        public Nullable<System.DateTime> InformDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
