//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SNSDataContext : DbContext
    {
        public SNSDataContext()
            : base("name=SNSDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Phone_Verify> tbl_Phone_Verify { get; set; }
        public DbSet<Routes> Routes { get; set; }
        public DbSet<Route_Matrix> Route_Matrix { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<User_Comment> User_Comment { get; set; }
        public DbSet<User_External> User_External { get; set; }
        public DbSet<User_Import> User_Import { get; set; }
        public DbSet<User_Order> User_Order { get; set; }
        public DbSet<User_Promotion> User_Promotion { get; set; }
        public DbSet<User_PromotionChannel> User_PromotionChannel { get; set; }
        public DbSet<User_Rate> User_Rate { get; set; }
        public DbSet<User_Route> User_Route { get; set; }
        public DbSet<User_Track> User_Track { get; set; }
        public DbSet<WeChatMessage> WeChatMessages { get; set; }
    }
}
