//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNS.Apps.KPC.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Order
    {
        public long ID { get; set; }
        public string Folio { get; set; }
        public long RequestorID { get; set; }
        public int RequestorRole { get; set; }
        public long SupplierID { get; set; }
        public int SupplierRole { get; set; }
        public long RouteID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsConfirmed_Requestor { get; set; }
        public Nullable<bool> IsConfirmed_Supplier { get; set; }
        public Nullable<bool> IsCancelled_Requestor { get; set; }
        public Nullable<bool> IsCancelled_Supplier { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
